---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: nzbhydra-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :5076
    repo: nzbhydra-dev
    run_args: -e SUID=0

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: nzbhydra-dev
    repo: spritsail/nzbhydra
    tags:
    - latest
    - "%label io.spritsail.version.nzbhydra | %auto"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 1be31bf8afcd798187ecb2033a91c2014a79fe5a976c18049730fc3599ff5b7d

...
