pipeline:
  build:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --no-cache --pull -t hydra-dev .

  test:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run --rm -dt -e SUID=0 hydra-dev)
      - timeout -t 15 docker logs -f $$CON_NAME &
      - sleep 10
      - IPADDR=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - curl -L --max-time 3 --retry 5 --retry-delay 5 --retry-connrefused $$IPADDR:5075  > /dev/null 
      - docker kill $$CON_NAME # Not really needed, but keeps things quick

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    when:
      event: [push, tag, deployment]
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - apk add --no-cache openssl jq
       - export CURVER=$(wget -O- https://api.github.com/repos/theotherp/nzbhydra/releases/latest | jq -r .tag_name)
         # Grab just the version, not the hash. Used for tagging
       - echo $DOCKER_USER
       - docker tag hydra-dev adamant/nzbhydra:latest
       - docker tag hydra-dev adamant/nzbhydra:$CURVER
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/nzbhydra
       - docker rmi hydra-dev adamant/nzbhydra
       - echo "CONGRATS! SUCCESSFULLY BUILT SICKRAGE!"
